PRODUCT_VERSION_MAJOR = 13
PRODUCT_VERSION_MINOR = 0

# Increase CR Version with each major release.
CELESTIA_VERSION := 1.0

# Codename Package
CELESTIA_CODENAME := Cosmic

# Celestia Versioning
CELESTIA_MAINTAINER ?= UNKNOWN
CELESTIA_MAINTAINER_LINK ?= UNKNOWN

# Internal version
LINEAGE_VERSION := CelestiaAOSP-v$(CELESTIA_VERSION)-$(CELESTIA_CODENAME)-$(PRODUCT_VERSION_MAJOR)-$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)-$(shell date +%Y%m%d)

# Display version
LINEAGE_DISPLAY_VERSION := CelestiaAOSP-v$(CELESTIA_VERSION)-$(CELESTIA_CODENAME)-$(PRODUCT_VERSION_MAJOR)-$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)

# System Version
PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
  ro.celestia.maintainer=$(CELESTIA_MAINTAINER) \
  ro.celestia.maintainer_link=$(CELESTIA_MAINTAINER_LINK)
